services:

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    ports:
      - "8368:2368"
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: "mysql"
      database__connection__host: "192.168.1.88"
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: "ghost"
      # this url value is just an example, and is likely wrong for your environment!
      url: "https://blog-rpg.baenalaux.org/"
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
      mail__from: lauripaulo@gmail.com
      security__staffDeviceVerification: false
    volumes:
      - /DATA/ghost/content:/var/lib/ghost/content

networks:
  homelab:
    external: true