# Docker Compose file for Flatnotes
# Reference: https://hub.docker.com/r/dullage/flatnotes


services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "user"
      FLATNOTES_PASSWORD: "changeMe!"
      FLATNOTES_SECRET_KEY: "I want to keep flatnotes as simple and distraction-free as possible which means limiting new features. This said, I welcome feedback and suggestions."
    volumes:
      - "/DATA/flatnotes:/data"
    ports:
      - "8321:8080"
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    external: true
